CREATE TABLE UserRole (
	id INT AUTO_INCREMENT PRIMARY KEY,
    roleName VARCHAR(20) NOT NULL
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE UserGender (
	id INT AUTO_INCREMENT PRIMARY KEY,
    genderName VARCHAR(20) NOT NULL
) DEFAULT CHARSET=utf8mb4;


CREATE TABLE Users (
	id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(400) UNIQUE NOT NULL,
    phoneNumber BIGINT UNSIGNED,
    firstName VARCHAR(100),
    lastName VARCHAR(100),
    genderId INT,
    userRoleId INT NOT NULL,
    passwordHash VARCHAR(200) NOT NULL,
    salt VARCHAR(500) NOT NULL,
    country VARCHAR(50),
    city VARCHAR(50),
    zip INT UNSIGNED,
    address VARCHAR(500),
    INDEX(phoneNumber),
    CONSTRAINT FK_UserRole FOREIGN KEY (userRoleId) REFERENCES UserRole(id),
    CONSTRAINT FK_UserGender FOREIGN KEY (genderId) REFERENCES UserGender(id)
) DEFAULT CHARSET=utf8mb4;


CREATE TABLE OrderStatus (
	id INT AUTO_INCREMENT PRIMARY KEY,
    statusName VARCHAR(50) NOT NULL
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE Orders (
	id INT AUTO_INCREMENT PRIMARY KEY,
    orderDate TIMESTAMP NOT NULL,
    statusId INT NOT NULL,
    userId INT NOT NULL,
    comment VARCHAR(500),
    INDEX(orderDate),
    CONSTRAINT FK_OrderStatus FOREIGN KEY (statusId) REFERENCES OrderStatus(id),
    CONSTRAINT FK_Users FOREIGN KEY (userId) REFERENCES Users(id)
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE PhotoStatus (
	id INT AUTO_INCREMENT PRIMARY KEY,
    statusName VARCHAR(50) NOT NULL
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE OrderPhotos (
	id INT AUTO_INCREMENT PRIMARY KEY,
    source VARCHAR(200) NOT NULL,
    orderId INT NOT NULL,
    photoStatusId INT NOT NULL,
    CONSTRAINT FK_Orders FOREIGN KEY (orderId) REFERENCES Orders(id),
    CONSTRAINT FK_PhotoStatus FOREIGN KEY (photoStatusId) REFERENCES PhotoStatus(id)
) DEFAULT CHARSET=utf8mb4;
